import React, { useState } from "react";
import { 
  ResponsiveContainer, 
  ComposedChart, 
  Line, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  Area 
} from "recharts";
import { 
  TrendingUp, 
  ShieldCheck, 
  DollarSign, 
  Activity, 
  Clock, 
  Download, 
  Calendar, 
  Filter, 
  ArrowUpRight,
  Zap,
  CheckCircle2
} from "lucide-react";
import { GlobalState } from "../types";
import { useLanguage } from "../App";

interface PerformanceMetricsChartProps {
  state?: GlobalState;
  isDark?: boolean;
}

const PERFORMANCE_DATA = [
  { month: "Jan", uptime: 98.4, savings: 12.4, downtime: 11.5, predictiveAccuracy: 91.2 },
  { month: "Feb", uptime: 98.7, savings: 15.1, downtime: 9.8, predictiveAccuracy: 92.5 },
  { month: "Mar", uptime: 99.1, savings: 18.2, downtime: 7.2, predictiveAccuracy: 94.1 },
  { month: "Apr", uptime: 98.9, savings: 16.5, downtime: 8.4, predictiveAccuracy: 93.8 },
  { month: "May", uptime: 99.4, savings: 22.8, downtime: 4.3, predictiveAccuracy: 96.2 },
  { month: "Jun", uptime: 99.2, savings: 24.1, downtime: 5.1, predictiveAccuracy: 95.9 },
  { month: "Jul", uptime: 99.6, savings: 29.5, downtime: 2.8, predictiveAccuracy: 98.1 },
  { month: "Aug", uptime: 99.5, savings: 31.0, downtime: 3.2, predictiveAccuracy: 97.8 },
  { month: "Sep", uptime: 99.8, savings: 36.4, downtime: 1.1, predictiveAccuracy: 99.1 },
];

export default function PerformanceMetricsChart({ state, isDark = true }: PerformanceMetricsChartProps) {
  const { language } = useLanguage();
  const [timeRange, setTimeRange] = useState<"YTD" | "Q3" | "12M">("YTD");
  const [activeMetric, setActiveMetric] = useState<"combined" | "uptime" | "savings">("combined");
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = () => {
    setIsExporting(true);
    setTimeout(() => {
      setIsExporting(false);
      alert(language === "fr" ? "📊 Rapport de performances exporté avec succès (CSV/PDF)." : "📊 Performance Metrics report exported successfully as CSV/PDF.");
    }, 1200);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white shadow-xl relative overflow-hidden border border-indigo-900/40">
        <div className="absolute right-0 top-0 translate-x-12 -translate-y-12 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 relative z-10">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-xs font-mono font-bold uppercase tracking-wider border border-indigo-500/30">
                {language === "fr" ? "Analytique Recharts • Uptime & Économies de Coûts" : "Recharts Analytics • Asset Uptime & Cost Savings"}
              </span>
            </div>
            <h2 className="text-xl md:text-2xl font-bold tracking-tight">
              {language === "fr" ? "Tableau de Bord des Performances Industrielles & Maintenance" : "Industrial Performance & Maintenance Dashboard"}
            </h2>
            <p className="text-xs md:text-sm text-slate-300 max-w-2xl mt-1">
              {language === "fr"
                ? "Analyse prédictive de la disponibilité des équipements de fabrication et des économies cumulées générées par les interventions de maintenance préventive."
                : "Predictive analysis of manufacturing equipment availability and cumulative cost savings generated by preventive maintenance interventions."}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <div className="bg-slate-800/80 p-1 rounded-xl border border-slate-700 flex items-center">
              {(["YTD", "Q3", "12M"] as const).map((range) => (
                <button
                  key={range}
                  onClick={() => setTimeRange(range)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                    timeRange === range ? "bg-indigo-600 text-white shadow-sm" : "text-slate-300 hover:text-white"
                  }`}
                >
                  {range === "YTD" ? "Année 2026" : range === "Q3" ? "Q3 2026" : "12 Mois Glissants"}
                </button>
              ))}
            </div>

            <button
              onClick={handleExport}
              disabled={isExporting}
              className="px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition-all shadow-md flex items-center gap-2 cursor-pointer active:scale-95 shrink-0 disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              {isExporting ? "Export..." : "Exporter Rapport"}
            </button>
          </div>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-2 relative overflow-hidden">
          <div className="absolute top-4 right-4 p-2 rounded-xl bg-emerald-500/10 text-emerald-500">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div className="text-xs font-medium text-slate-500 dark:text-neutral-400">Disponibilité Moyenne (Uptime)</div>
          <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white flex items-center gap-2">
            99.28%
            <span className="text-xs font-sans text-emerald-600 dark:text-emerald-400 font-semibold bg-emerald-500/10 px-2 py-0.5 rounded-full flex items-center gap-0.5">
              <ArrowUpRight className="w-3 h-3" /> +0.65%
            </span>
          </div>
          <div className="text-[11px] text-slate-500">Objectif SLA global (&gt;99.0%)</div>
        </div>

        <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-2 relative overflow-hidden">
          <div className="absolute top-4 right-4 p-2 rounded-xl bg-indigo-500/10 text-indigo-500">
            <DollarSign className="w-5 h-5" />
          </div>
          <div className="text-xs font-medium text-slate-500 dark:text-neutral-400">Économies de Maintenance Cumulées</div>
          <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white flex items-center gap-2">
            187.8 k€
            <span className="text-xs font-sans text-indigo-600 dark:text-indigo-400 font-semibold bg-indigo-500/10 px-2 py-0.5 rounded-full flex items-center gap-0.5">
              <ArrowUpRight className="w-3 h-3" /> +28% y/y
            </span>
          </div>
          <div className="text-[11px] text-slate-500">Évitement d'arrêts de ligne non planifiés</div>
        </div>

        <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-2 relative overflow-hidden">
          <div className="absolute top-4 right-4 p-2 rounded-xl bg-amber-500/10 text-amber-500">
            <Clock className="w-5 h-5" />
          </div>
          <div className="text-xs font-medium text-slate-500 dark:text-neutral-400">Temps d'Arrêt Total (Downtime)</div>
          <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white flex items-center gap-2">
            44.6 h
            <span className="text-xs font-sans text-emerald-600 dark:text-emerald-400 font-semibold bg-emerald-500/10 px-2 py-0.5 rounded-full flex items-center gap-0.5">
              -62% vs N-1
            </span>
          </div>
          <div className="text-[11px] text-slate-500">Heures cumulées sur toutes les lignes</div>
        </div>

        <div className="p-5 rounded-2xl bg-white dark:bg-neutral-900 border border-slate-200 dark:border-neutral-800 shadow-sm space-y-2 relative overflow-hidden">
          <div className="absolute top-4 right-4 p-2 rounded-xl bg-purple-500/10 text-purple-500">
            <Zap className="w-5 h-5" />
          </div>
          <div className="text-xs font-medium text-slate-500 dark:text-neutral-400">Précision de Maintenance Prédictive</div>
          <div className="text-2xl font-bold font-mono text-slate-900 dark:text-white flex items-center gap-2">
            96.4%
            <span className="text-xs font-sans text-purple-600 dark:text-purple-400 font-semibold bg-purple-500/10 px-2 py-0.5 rounded-full flex items-center gap-0.5">
              <ArrowUpRight className="w-3 h-3" /> +4.2%
            </span>
          </div>
          <div className="text-[11px] text-slate-500">Capteurs IoT & modélisation MES</div>
        </div>
      </div>

      {/* Main Recharts Dashboard Section */}
      <div className="rounded-2xl border border-slate-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm p-6 space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-neutral-800">
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-indigo-500" />
              Évolution de l'Uptime et des Économies de Maintenance (Recharts)
            </h3>
            <p className="text-xs text-slate-500 dark:text-neutral-400 mt-0.5">
              Corrélation temporelle entre la disponibilité des équipements (%) et les économies de coûts cumulées (en k€).
            </p>
          </div>

          <div className="flex items-center gap-1.5 bg-slate-100 dark:bg-neutral-800 p-1 rounded-xl border border-slate-200 dark:border-neutral-700">
            <button
              onClick={() => setActiveMetric("combined")}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors cursor-pointer ${
                activeMetric === "combined" ? "bg-indigo-600 text-white shadow-xs" : "text-slate-600 dark:text-neutral-400 hover:text-white"
              }`}
            >
              Vue Combinée
            </button>
            <button
              onClick={() => setActiveMetric("uptime")}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors cursor-pointer ${
                activeMetric === "uptime" ? "bg-indigo-600 text-white shadow-xs" : "text-slate-600 dark:text-neutral-400 hover:text-white"
              }`}
            >
              Uptime (%)
            </button>
            <button
              onClick={() => setActiveMetric("savings")}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors cursor-pointer ${
                activeMetric === "savings" ? "bg-indigo-600 text-white shadow-xs" : "text-slate-600 dark:text-neutral-400 hover:text-white"
              }`}
            >
              Économies (k€)
            </button>
          </div>
        </div>

        {/* Recharts Composed Chart */}
        <div className="w-full h-80 pt-4">
          <ResponsiveContainer width="100%" height="100%">
            <ComposedChart data={PERFORMANCE_DATA} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#262626" : "#e2e8f0"} />
              <XAxis dataKey="month" stroke={isDark ? "#a3a3a3" : "#64748b"} fontSize={12} />
              <YAxis 
                yAxisId="left" 
                orientation="left" 
                domain={[97, 100]} 
                stroke={isDark ? "#818cf8" : "#4f46e5"} 
                fontSize={12}
                unit="%"
              />
              <YAxis 
                yAxisId="right" 
                orientation="right" 
                domain={[0, 45]} 
                stroke={isDark ? "#34d399" : "#059669"} 
                fontSize={12}
                unit="k€"
              />
              <Tooltip 
                contentStyle={{ 
                  backgroundColor: isDark ? "#171717" : "#ffffff", 
                  borderColor: isDark ? "#262626" : "#e2e8f0", 
                  borderRadius: "12px",
                  color: isDark ? "#ffffff" : "#0f172a",
                  fontSize: "12px"
                }} 
              />
              <Legend wrapperStyle={{ fontSize: "12px", paddingTop: "12px" }} />
              
              {(activeMetric === "combined" || activeMetric === "savings") && (
                <Bar 
                  yAxisId="right" 
                  dataKey="savings" 
                  name="Économies de Maintenance (k€)" 
                  fill="#6366f1" 
                  radius={[6, 6, 0, 0]} 
                  barSize={28} 
                />
              )}
              
              {(activeMetric === "combined" || activeMetric === "uptime") && (
                <Line 
                  yAxisId="left" 
                  type="monotone" 
                  dataKey="uptime" 
                  name="Disponibilité Équipements (Uptime %)" 
                  stroke="#10b981" 
                  strokeWidth={3} 
                  dot={{ r: 4, fill: "#10b981" }} 
                  activeDot={{ r: 6 }} 
                />
              )}

              <Line 
                yAxisId="left" 
                type="monotone" 
                dataKey="predictiveAccuracy" 
                name="Précision Prédictive (%)" 
                stroke="#a855f7" 
                strokeWidth={2} 
                strokeDasharray="4 4" 
                dot={false} 
              />
            </ComposedChart>
          </ResponsiveContainer>
        </div>

        {/* Bottom Insight Notes */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t border-slate-100 dark:border-neutral-800 text-xs text-slate-600 dark:text-neutral-400">
          <div className="flex items-start gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
            <div>
              <span className="font-semibold text-slate-900 dark:text-white">Corrélation Directe :</span> L'automatisation des interventions préventives réduit de 62% les temps d'arrêt non planifiés.
            </div>
          </div>
          <div className="flex items-start gap-2.5">
            <Zap className="w-4 h-4 text-indigo-500 shrink-0 mt-0.5" />
            <div>
              <span className="font-semibold text-slate-900 dark:text-white">ROI Accéléré :</span> 187.8 k€ d'économies nettes enregistrées sur les 9 derniers mois grâce à l'analyse IoT.
            </div>
          </div>
          <div className="flex items-start gap-2.5">
            <Activity className="w-4 h-4 text-purple-500 shrink-0 mt-0.5" />
            <div>
              <span className="font-semibold text-slate-900 dark:text-white">Modèle Prédictif :</span> Taux de précision des capteurs thermiques et vibratoires stabilisé au-dessus de 98% depuis juillet.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
